name: kuunganatask
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.5
  flutter_svg: ^2.0.0 
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^6.1.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.8.0
  phone_form_field: ^7.1.0
  pin_code_fields: ^7.4.0
  riverpod_annotation: ^2.1.0
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  email_validator: '^2.1.16'
  go_router: ^6.5.8
  tab_indicator_styler: ^2.0.0
  avatar_stack: ^1.2.0
  percent_indicator: ^4.2.3
  popover: ^0.2.8+2
  custom_pop_up_menu: ^1.2.4
  dotted_border: ^2.0.0+3
  flutter_material_color_picker: ^1.1.0+2
  

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat Regular 400.ttf
        - asset: assets/fonts/Montserrat Medium 500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat SemiBold 600.ttf
          weight: 600
        - asset: assets/fonts/Montserrat Bold 700.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
